name: Build Documentation

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  pages: write
  id-token: write

env:
  INSTANCE: Writerside/rabbitmq
  DOCKER_VERSION: 243.21565

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build documentation
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Debug - List artifacts directory
        run: |
          ls -la
          ls -la artifacts/ || echo "artifacts directory not found"
          find . -name "*.zip" || echo "No zip files found"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: artifacts/*.zip
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docs

      - name: List downloaded files
        run: ls -la

      - name: Unzip artifact
        run: |
          unzip -l *.zip
          unzip -O UTF-8 -qq *.zip -d docs

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4